// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Seq string `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Message_Ping
	//	*Message_Ack
	//	*Message_IndirectPing
	Payload              isMessage_Payload `protobuf_oneof:"payload"`
	PiggyBackData        *PiggyBackData    `protobuf:"bytes,5,opt,name=piggy_back_data,json=piggyBackData,proto3" json:"piggy_back_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSeq() string {
	if m != nil {
		return m.Seq
	}
	return ""
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type Message_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type Message_IndirectPing struct {
	IndirectPing *IndirectPing `protobuf:"bytes,4,opt,name=indirect_ping,json=indirectPing,proto3,oneof"`
}

func (*Message_Ping) isMessage_Payload() {}

func (*Message_Ack) isMessage_Payload() {}

func (*Message_IndirectPing) isMessage_Payload() {}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetPing() *Ping {
	if x, ok := m.GetPayload().(*Message_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *Message) GetAck() *Ack {
	if x, ok := m.GetPayload().(*Message_Ack); ok {
		return x.Ack
	}
	return nil
}

func (m *Message) GetIndirectPing() *IndirectPing {
	if x, ok := m.GetPayload().(*Message_IndirectPing); ok {
		return x.IndirectPing
	}
	return nil
}

func (m *Message) GetPiggyBackData() *PiggyBackData {
	if m != nil {
		return m.PiggyBackData
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_Ping)(nil),
		(*Message_Ack)(nil),
		(*Message_IndirectPing)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_Ping:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ping); err != nil {
			return err
		}
	case *Message_Ack:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ack); err != nil {
			return err
		}
	case *Message_IndirectPing:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IndirectPing); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Payload has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 2: // payload.ping
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ping)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_Ping{msg}
		return true, err
	case 3: // payload.ack
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ack)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_Ack{msg}
		return true, err
	case 4: // payload.indirect_ping
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IndirectPing)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_IndirectPing{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_Ping:
		s := proto.Size(x.Ping)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Ack:
		s := proto.Size(x.Ack)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_IndirectPing:
		s := proto.Size(x.IndirectPing)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Ack struct {
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type IndirectPing struct {
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Nack                 bool     `protobuf:"varint,3,opt,name=nack,proto3" json:"nack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndirectPing) Reset()         { *m = IndirectPing{} }
func (m *IndirectPing) String() string { return proto.CompactTextString(m) }
func (*IndirectPing) ProtoMessage()    {}
func (*IndirectPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *IndirectPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndirectPing.Unmarshal(m, b)
}
func (m *IndirectPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndirectPing.Marshal(b, m, deterministic)
}
func (m *IndirectPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndirectPing.Merge(m, src)
}
func (m *IndirectPing) XXX_Size() int {
	return xxx_messageInfo_IndirectPing.Size(m)
}
func (m *IndirectPing) XXX_DiscardUnknown() {
	xxx_messageInfo_IndirectPing.DiscardUnknown(m)
}

var xxx_messageInfo_IndirectPing proto.InternalMessageInfo

func (m *IndirectPing) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *IndirectPing) GetNack() bool {
	if m != nil {
		return m.Nack
	}
	return false
}

type PiggyBackData struct {
	// Types that are valid to be assigned to Payload:
	//	*PiggyBackData_Alive
	//	*PiggyBackData_Suspect
	//	*PiggyBackData_Dead
	Payload              isPiggyBackData_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PiggyBackData) Reset()         { *m = PiggyBackData{} }
func (m *PiggyBackData) String() string { return proto.CompactTextString(m) }
func (*PiggyBackData) ProtoMessage()    {}
func (*PiggyBackData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *PiggyBackData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PiggyBackData.Unmarshal(m, b)
}
func (m *PiggyBackData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PiggyBackData.Marshal(b, m, deterministic)
}
func (m *PiggyBackData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PiggyBackData.Merge(m, src)
}
func (m *PiggyBackData) XXX_Size() int {
	return xxx_messageInfo_PiggyBackData.Size(m)
}
func (m *PiggyBackData) XXX_DiscardUnknown() {
	xxx_messageInfo_PiggyBackData.DiscardUnknown(m)
}

var xxx_messageInfo_PiggyBackData proto.InternalMessageInfo

type isPiggyBackData_Payload interface {
	isPiggyBackData_Payload()
}

type PiggyBackData_Alive struct {
	Alive *Alive `protobuf:"bytes,1,opt,name=alive,proto3,oneof"`
}

type PiggyBackData_Suspect struct {
	Suspect *Suspect `protobuf:"bytes,2,opt,name=suspect,proto3,oneof"`
}

type PiggyBackData_Dead struct {
	Dead *Dead `protobuf:"bytes,3,opt,name=dead,proto3,oneof"`
}

func (*PiggyBackData_Alive) isPiggyBackData_Payload() {}

func (*PiggyBackData_Suspect) isPiggyBackData_Payload() {}

func (*PiggyBackData_Dead) isPiggyBackData_Payload() {}

func (m *PiggyBackData) GetPayload() isPiggyBackData_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PiggyBackData) GetAlive() *Alive {
	if x, ok := m.GetPayload().(*PiggyBackData_Alive); ok {
		return x.Alive
	}
	return nil
}

func (m *PiggyBackData) GetSuspect() *Suspect {
	if x, ok := m.GetPayload().(*PiggyBackData_Suspect); ok {
		return x.Suspect
	}
	return nil
}

func (m *PiggyBackData) GetDead() *Dead {
	if x, ok := m.GetPayload().(*PiggyBackData_Dead); ok {
		return x.Dead
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PiggyBackData) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PiggyBackData_OneofMarshaler, _PiggyBackData_OneofUnmarshaler, _PiggyBackData_OneofSizer, []interface{}{
		(*PiggyBackData_Alive)(nil),
		(*PiggyBackData_Suspect)(nil),
		(*PiggyBackData_Dead)(nil),
	}
}

func _PiggyBackData_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PiggyBackData)
	// payload
	switch x := m.Payload.(type) {
	case *PiggyBackData_Alive:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Alive); err != nil {
			return err
		}
	case *PiggyBackData_Suspect:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Suspect); err != nil {
			return err
		}
	case *PiggyBackData_Dead:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Dead); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PiggyBackData.Payload has unexpected type %T", x)
	}
	return nil
}

func _PiggyBackData_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PiggyBackData)
	switch tag {
	case 1: // payload.alive
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Alive)
		err := b.DecodeMessage(msg)
		m.Payload = &PiggyBackData_Alive{msg}
		return true, err
	case 2: // payload.suspect
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Suspect)
		err := b.DecodeMessage(msg)
		m.Payload = &PiggyBackData_Suspect{msg}
		return true, err
	case 3: // payload.dead
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Dead)
		err := b.DecodeMessage(msg)
		m.Payload = &PiggyBackData_Dead{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PiggyBackData_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PiggyBackData)
	// payload
	switch x := m.Payload.(type) {
	case *PiggyBackData_Alive:
		s := proto.Size(x.Alive)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PiggyBackData_Suspect:
		s := proto.Size(x.Suspect)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PiggyBackData_Dead:
		s := proto.Size(x.Dead)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Alive struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alive) Reset()         { *m = Alive{} }
func (m *Alive) String() string { return proto.CompactTextString(m) }
func (*Alive) ProtoMessage()    {}
func (*Alive) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *Alive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alive.Unmarshal(m, b)
}
func (m *Alive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alive.Marshal(b, m, deterministic)
}
func (m *Alive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alive.Merge(m, src)
}
func (m *Alive) XXX_Size() int {
	return xxx_messageInfo_Alive.Size(m)
}
func (m *Alive) XXX_DiscardUnknown() {
	xxx_messageInfo_Alive.DiscardUnknown(m)
}

var xxx_messageInfo_Alive proto.InternalMessageInfo

type Suspect struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Suspect) Reset()         { *m = Suspect{} }
func (m *Suspect) String() string { return proto.CompactTextString(m) }
func (*Suspect) ProtoMessage()    {}
func (*Suspect) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *Suspect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suspect.Unmarshal(m, b)
}
func (m *Suspect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suspect.Marshal(b, m, deterministic)
}
func (m *Suspect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suspect.Merge(m, src)
}
func (m *Suspect) XXX_Size() int {
	return xxx_messageInfo_Suspect.Size(m)
}
func (m *Suspect) XXX_DiscardUnknown() {
	xxx_messageInfo_Suspect.DiscardUnknown(m)
}

var xxx_messageInfo_Suspect proto.InternalMessageInfo

type Dead struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dead) Reset()         { *m = Dead{} }
func (m *Dead) String() string { return proto.CompactTextString(m) }
func (*Dead) ProtoMessage()    {}
func (*Dead) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *Dead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dead.Unmarshal(m, b)
}
func (m *Dead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dead.Marshal(b, m, deterministic)
}
func (m *Dead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dead.Merge(m, src)
}
func (m *Dead) XXX_Size() int {
	return xxx_messageInfo_Dead.Size(m)
}
func (m *Dead) XXX_DiscardUnknown() {
	xxx_messageInfo_Dead.DiscardUnknown(m)
}

var xxx_messageInfo_Dead proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*Ping)(nil), "pb.Ping")
	proto.RegisterType((*Ack)(nil), "pb.Ack")
	proto.RegisterType((*IndirectPing)(nil), "pb.IndirectPing")
	proto.RegisterType((*PiggyBackData)(nil), "pb.PiggyBackData")
	proto.RegisterType((*Alive)(nil), "pb.Alive")
	proto.RegisterType((*Suspect)(nil), "pb.Suspect")
	proto.RegisterType((*Dead)(nil), "pb.Dead")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x93, 0x26, 0x6d, 0x9a, 0x6b, 0x23, 0x8a, 0x07, 0x14, 0x09, 0x09, 0x4a, 0x16, 0x3a,
	0x75, 0x28, 0x03, 0x82, 0xad, 0x55, 0x87, 0x30, 0x20, 0x21, 0xf3, 0x00, 0xd5, 0xc5, 0xb1, 0x2c,
	0x2b, 0x25, 0x35, 0x8d, 0x41, 0xca, 0x0b, 0xf0, 0x8a, 0xbc, 0x0e, 0xb2, 0xe3, 0x56, 0x61, 0xbb,
	0xfb, 0xff, 0x3f, 0x97, 0xbb, 0xcf, 0x90, 0x7c, 0xf0, 0xa6, 0x41, 0xc1, 0x97, 0xea, 0x78, 0xd0,
	0x07, 0x32, 0x50, 0x45, 0xf6, 0xeb, 0x43, 0xf4, 0xda, 0xa9, 0x64, 0x06, 0x41, 0xc3, 0x3f, 0x53,
	0x7f, 0xee, 0x2f, 0x62, 0x6a, 0x4a, 0x72, 0x03, 0xa1, 0x92, 0xb5, 0x48, 0x07, 0x73, 0x7f, 0x31,
	0x59, 0x8d, 0x97, 0xaa, 0x58, 0xbe, 0xc9, 0x5a, 0xe4, 0x1e, 0xb5, 0x3a, 0xb9, 0x86, 0x00, 0x59,
	0x95, 0x06, 0xd6, 0x8e, 0x8c, 0xbd, 0x66, 0x55, 0xee, 0x51, 0xa3, 0x92, 0x47, 0x48, 0x64, 0x5d,
	0xca, 0x23, 0x67, 0x7a, 0x67, 0xa7, 0x84, 0x36, 0x36, 0x33, 0xb1, 0x17, 0x67, 0xb8, 0x69, 0x53,
	0xd9, 0xeb, 0xc9, 0x13, 0x5c, 0x28, 0x29, 0x44, 0xbb, 0x2b, 0x90, 0x55, 0xbb, 0x12, 0x35, 0xa6,
	0x43, 0xfb, 0xe9, 0x65, 0xb7, 0x80, 0x10, 0xed, 0x06, 0x59, 0xb5, 0x45, 0x8d, 0x34, 0x51, 0xfd,
	0x76, 0x13, 0x43, 0xa4, 0xb0, 0xdd, 0x1f, 0xb0, 0xcc, 0x46, 0x10, 0x9a, 0x69, 0xd9, 0x2d, 0x04,
	0x6b, 0x56, 0x91, 0xf4, 0xec, 0xd8, 0x6b, 0x62, 0x7a, 0x0e, 0x3e, 0xc3, 0xb4, 0xbf, 0x0e, 0xb9,
	0x82, 0x91, 0xc6, 0xa3, 0xe0, 0xda, 0x05, 0x5d, 0x47, 0x08, 0x84, 0xf5, 0xe9, 0xda, 0x31, 0xb5,
	0x75, 0xf6, 0xe3, 0x43, 0xf2, 0x6f, 0x21, 0x72, 0x07, 0x43, 0xdc, 0xcb, 0x6f, 0x6e, 0x31, 0x4e,
	0x56, 0xb1, 0x85, 0x62, 0x84, 0xdc, 0xa3, 0x9d, 0x43, 0xee, 0x21, 0x6a, 0xbe, 0x1a, 0xc5, 0x99,
	0x76, 0x60, 0x27, 0x26, 0xf4, 0xde, 0x49, 0xb9, 0x47, 0x4f, 0xae, 0xc1, 0x5f, 0x72, 0x2c, 0x1d,
	0x5f, 0x8b, 0x7f, 0xcb, 0xb1, 0x34, 0xf8, 0x8d, 0xde, 0xbf, 0x36, 0x82, 0xa1, 0xfd, 0x4b, 0x16,
	0x43, 0xe4, 0x26, 0x19, 0x02, 0x26, 0x5e, 0x8c, 0xec, 0x73, 0x3f, 0xfc, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x5d, 0x0d, 0xa2, 0xab, 0xff, 0x01, 0x00, 0x00,
}
